[project]
name = "generative-recs"
version = "0.1.0"
description = "Build, train, and evaluate generative recommender systems"
readme = "README.md"
authors = [
    { name = "Milutin Studen", email = "81291567+milistu@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.13.0",
    "duckdb>=1.5.1",
    "loguru>=0.7.3",
    "matplotlib>=3.10.8",
    "mmh3>=5.2.1",
    "pandas>=3.0.1",
    "pyarrow>=23.0.1",
    "pydantic>=2.13.5",
    "pyyaml>=6.0.3",
    "sentence-transformers>=5.3.0",
    "torch>=2.11.0",
    "tqdm>=4.67.3",
    "transformers>=5.3.0",
    "typer>=0.27.2",
    "vector-quantize-pytorch>=1.28.0",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "pre-commit>=4.6.2",
    "ruff>=0.17.0",
]

[tool.ruff]
line-length = 100
target-version = "py312"
extend-exclude = ["*.ipynb"]

[tool.ruff.lint]
select = ["E", "F", "I", "UP"]

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = ""
